// Generated by https://quicktype.io

export interface IBondIssureItemResponse {
  timestamp: number;
  success: boolean;
  message: string;
  data: IBondIssuerItem[];
}

export interface IBondIssuerItem {
  yearOfBondIssued: string;
  typeOfInstruments: string;
  term: string;
  couponRate: string;
  interestPayment: string;
  taxTreatment: string;
  repayment: string;
  dateOfIssue: string;
  maturityDate: string;
  platform: string;
  type: string;
  issueSize: string;
  bidsReceived: string;
  amountAccepted: string;
  greenShoeOption: string;
  greenShowOptionAmount: string;
  guaranteedByStateGovernment: string;
  guaranteeMechanism: string;
  crisil: string;
  care: string;
  icra: string;
  brickwork: string;
  "auicte/Smera": string;
  "indiaRatings&Research": string;
  linksToReports: string;
  objectOfIssue: string;
  whoCanInvest: string;
  detailsOfSubscribers: string;
  transactionAdvisors: string;
  trusteeForTheBond: string;
  registrarOfTheIssue: string;
  auditorOfIssue: string;
  legalCounsel: string;
  escrowBanker: string;
  arranger: string;
  draftInformationMemorandum: string;
  noticesFromPlatforms: string;
  others: string;
  modifiedAt: string;
  createdAt: string;
  isActive: boolean;
  _id: string;
  ulb: string;
  __v: number;
}

export enum AmountAccepted {
  AmountAcceptedINR200Crores = "INR 200 Crores",
  Empty = "",
  INR13990Crores = "INR 139.90 crores",
  INR2000Crores = "INR 2000 crores",
  INR200Crores = "INR 200 crores",
  NotAvailable = "Not Available"
}

export enum Arranger {
  AKCapitalServices = "AK Capital Services",
  Empty = "",
  NotAvailable = "Not Available",
  SBICapitalMarket = "SBI Capital Market",
  The30ArrangerDetailsNotAvailable = "30 arranger. Details not available"
}

export enum AuditorOfIssue {
  AuditorOfIssueNotAvailable = "Not Available",
  Empty = "",
  NatvarlalVepariCo = "Natvarlal Vepari & Co",
  NotAvailable = "Not available",
  ResidentialAuditDepartmentIndoreMunicipalCorporation = "Residential Audit Department, Indore Municipal Corporation",
  StateAuditDepartment = "State Audit Department"
}

export enum AuicteSmera {
  A = "A-",
  Aa = "AA-",
  AaSo = "AA (SO)",
  AuicteSmeraAA = "AA",
  AuicteSmeraNotApplicable = "Not Applicable",
  Empty = "",
  NotApplicable = "Not applicable"
}

export enum Care {
  AAStable = "AA+ / Stable",
  Aa = "AA",
  CareAA = "AA+",
  CareAAStable = "AA / Stable",
  CareNotApplicable = "Not applicable",
  Empty = "",
  NotApplicable = "Not Applicable"
}

export enum EscrowBanker {
  BankOfMaharashtra = "Bank of Maharashtra",
  Empty = "",
  EscrowBankerNotAvailable = "Not available",
  KotakMahindraBankLimited = "Kotak Mahindra Bank Limited",
  NotAvailable = "Not Available"
}

export enum GreenSho {
  Empty = "",
  INR100Crores = "INR 100 Crores",
  INR700Crores = "INR 700 crores",
  INR70Crores = "INR 70 crores",
  NotApplicable = "Not Applicable",
  NotAvailable = "Not available",
  Yes = "Yes"
}

export enum GuaranteedByStateGovernment {
  Empty = "",
  No = "No",
  NotAvailable = "Not Available",
  Yes = "Yes"
}

export enum Icra {
  AAA = "AAA",
  Aa = "AA+",
  Empty = "",
  IcraAA = "AA",
  IcraNotApplicable = "Not applicable",
  NotApplicable = "Not Applicable"
}

export enum LegalCounsel {
  Empty = "",
  LegalCounselMVKiniLawFirm = "MV Kini Law Firm",
  LegalCounselNotAvailable = "Not Available",
  MVKiniLawFirm = "MVKini Law Firm",
  NotAvailable = "Not available"
}

export enum Platform {
  BSEBondPlatform = "BSE Bond platform",
  Bse = "BSE",
  DebtSecuritiesPlatformOfNSE = "Debt securities platform of NSE",
  Empty = "",
  Nse = "NSE"
}

export enum RegistrarOfTheIssue {
  Empty = "",
  KarvyComputersharePrivateLimited = "Karvy Computershare Private Limited",
  KarvyFinTech = "Karvy FinTech",
  NotAvailable = "Not available",
  RegistrarOfTheIssueNotAvailable = "Not Available"
}

export enum TaxTreatment {
  Empty = "",
  NonTaxable = "Non- Taxable",
  TaxTreatmentNonTaxable = "Non-Taxable",
  Taxable = "Taxable"
}

export enum TrusteeForTheBond {
  CatalystTrusteeshipLimited = "Catalyst Trusteeship Limited",
  Empty = "",
  NotAvailable = "Not available",
  SBICAPTrusteeCompanyLimited = "SBICAP Trustee Company Limited",
  TrusteeForTheBondNotAvailable = "Not Available",
  VistraITCLIndiaLimited = "Vistra ITCL (India) Limited"
}

export enum Type {
  Empty = "",
  Private = "Private",
  PrivatePlacement = "Private Placement",
  PublicPrivate = "Public & Private"
}
