import { RESTRICTION, VALIDATION } from "./constants";

export const restrictions = [...Object.values(RESTRICTION)];
export const validations = [...Object.values(VALIDATION)];

export const restrictionChangingValues = [
  RESTRICTION.LESS_THAN,
  RESTRICTION.LESS_THAN_EQUAL,
  RESTRICTION.EQUAL_TO,
  RESTRICTION.GREATER_THAN,
  RESTRICTION.GREAT_THAN_EQUAL,
  RESTRICTION.BACKEND_SUM,
  RESTRICTION.ADDITION,
  RESTRICTION.SUBTRACTION,
  RESTRICTION.MULTIPLICATION,
  RESTRICTION.DIVISION,
  RESTRICTION.SUM_FROM_LOOP,
];
