import { USER_TYPE } from 'src/app/models/user/userType';
import { ULBSIGNUPSTATUS } from 'src/app/util/enums';

import { IBaseProfileData } from './base-profile';

export enum fieldNameWithFileRequirement {
  TYPE = "type",
  NoOfWards = "noOfWards",
  Population = "population",
  Area = "area",
  Name = "name",
}

// tslint:disable-next-line: interface-over-type-literal
export type FieldsWithFile = {
  [key in fieldNameWithFileRequirement]?: { file: File };
};
// Generated by https://quicktype.io

export interface IULBProfileData extends IBaseProfileData {
  mobile: string;
  email: string;
  accountantConatactNumber: string;
  accountantEmail: string;
  accountantName: string;
  commissionerConatactNumber: string;
  commissionerEmail: string;
  commissionerName: string;
  status: keyof typeof ULBSIGNUPSTATUS;
  ulb: Ulb;
  role: USER_TYPE.ULB;
  rejectReason?: string;
  isVerified2223?: boolean;
  isActive?:boolean;
}

export interface Ulb {
  wards: number;
  area: number;
  population: number;
  _id: string;
  code: string;
  name: string;
  state: State;
}

export interface State {
  _id: string;
  name: string;
  code: string;
}
